name: CD Development

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  #---------------------------------------------------------------------------------------------------------------------
  # DEPLOY - Ejecutar solo si todos los tests pasan
  #---------------------------------------------------------------------------------------------------------------------
  deploy:
    name: Deploy to development
    runs-on:
      - self-hosted
      - sportying-dev
    needs: [ snyk, codeql, quality, integration, e2e ]

    steps:
      - name: Show Docker version
        run: docker --version

      - name: Show Docker Compose version
        run: docker compose version

      - name: Update repository on server
        run: |
          cd /srv/apps/sportying_backend
          export GIT_SSH_COMMAND="ssh -i ~/.ssh/id_github -o StrictHostKeyChecking=no"
          git fetch origin
          git checkout dev
          git pull origin dev

      - name: Deploy development stack
        run: docker compose -f /srv/docker/compose/sportying/docker-compose.yml
          --profile dev up -d --build
